### ISSUE TITLE
Handle error when search result is empty

### ISSUE THREAD

**Issue by brainwo** [brainwo/yatta#14]
Search query:
```
lorem ipsum dolor sit amet asd jkl
```
Expected output: show result page saying it's empty 
Actual output: showing error page saying "Null check operator used on a null value"

**Comment by asif4318** [comment]
I would like to take care of this issue

**Comment by brainwo** [comment]
Oh hi @asif4318 I appreciate your offer. 😊

Currently I'm developing on `dev` branch, so that is the branch you should working on. `main` is currently outdated until I decided `dev` is good enough to be merged there.

If you need anything, you can hit me up on Discord. I'm in the Flutter Dev Discord you can ping me in the `#offtopic` channel there. If not, my other contact is also available in my profile (Discord/Matrix). You can also use the discussion page https://github.com/brainwo/yatta/discussions but note that I might not response as fast in GitHub.

Thanks in advance.

**Comment by asif4318** [comment]
Can you add me please on discord (username: ai50 )?

**Comment by brainwo** [comment]
Sure thing
